/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "kmeukjsytweuqkwwwkbr"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImttZXVranN5dHdldXFrd3d3a2JyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMyNjY1NjEsImV4cCI6MjA3ODg0MjU2MX0.kktipAcVguLW7U-W8rqaLqFm-RPWTuXOA9wFFE6wmcc"